dot_net_task_list:
    resource: "@DotNetTaskListBundle/Controller/"
    type:     annotation
    prefix:   /

kotpresence:
    resource: "@kotpresenceBundle/Resources/config/routing.yml"
    prefix:   /

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode