<?php

namespace kot\presenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * expensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class expensesRepository extends EntityRepository
{
}
