<?php

namespace kot\presenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * mactableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mactableRepository extends EntityRepository
{
}
